export const logo = 'https://assets.turbologo.com/blog/en/2021/07/23083922/anime-logo-958x575.png';

export const categories = [
  { name: 'Action' },
  { name: 'Adventure' },
  { name: 'Cars' },
  { name: 'Comedy' },
  { name: 'Crime' },
  { name: 'Dementia' },
  { name: 'Demons' },
  { name: 'Drama' },
  { name: 'Dub' },
  { name: 'Ecchi' },
  { name: 'Family' },
  { name: 'Fantasy' },
  { name: 'Game' },
  { name: 'Gourmet' },
  { name: 'Harem' },
  { name: 'Horror' },
  { name: 'Historical'},
  { name: 'Josei' },
  { name: 'Kids' },
  { name: 'Magic' },
  { name: 'Martial-Arts' },
  { name: 'Mecha' },
  { name: 'Military' },
  { name: 'Mystery' },
  { name: 'Parody' },
  { name: 'Police' },
  { name: 'Psychological' },
  { name: 'Romance' },
  { name: 'Samurai' },
  { name: 'School' },
  { name: 'Sci-fi' },
  { name: 'School' },
  { name: 'Seinen' },
  { name: 'Shoujo' },
  { name: 'Shoujo-Ai' },
  { name: 'Shounen' },
  { name: 'Shounen-Ai' },
  { name: 'Space' },
  { name: 'Sports' },
  { name: 'Super-power' },
  { name: 'Supernatural' },
  { name: 'Suspense' },
  { name: 'Thriller' }
];